# Generated by Django 5.1.4 on 2024-12-24 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_full_name', models.CharField(max_length=250)),
                ('new_email', models.CharField(max_length=300)),
                ('new_address1', models.CharField(blank=True, max_length=250)),
                ('new_address2', models.CharField(blank=True, max_length=250, null=True)),
                ('new_city', models.CharField(blank=True, max_length=25)),
                ('new_state', models.CharField(blank=True, max_length=25, null=True)),
                ('new_zipcode', models.CharField(blank=True, max_length=25, null=True)),
                ('new_country', models.CharField(default='IRAN', max_length=25)),
                ('old_cart', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Shipping Address',
            },
        ),
    ]
