# Generated by Django 5.1.4 on 2024-12-24 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newpayment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newshippingaddress',
            name='old_cart',
        ),
    ]
