# Generated by Django 5.1.2 on 2025-01-09 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newpayment', '0004_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='products',
            new_name='product',
        ),
    ]
